# Codemagic Build Configuration – Flutter 3.22.0 Stable (Android APK)

workflows:
  lottogenerator-android:
    name: Lottogenerator Android Build
    environment:
      flutter: "3.22.0"
      vars:
        PACKAGE_NAME: "com.example.lottogenerator_v3"

    scripts:
      - name: Flutter Version prüfen
        script: |
          flutter --version

      - name: Dependencies installieren
        script: |
          flutter pub get

      - name: Analyzer laufen lassen (Info-Warnungen ignorieren)
        script: |
          flutter analyze --no-pub --no-fatal-infos

      - name: Release APK bauen
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - funatiker1968@gmail.com
